[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules for Astro directory format
[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat/"
  status = 301
  force = false

# Ensure trailing slash handling for all pages
[[redirects]]
  from = "/*"
  to = "/*/index.html"
  status = 200