[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Force HTTPS redirect
[[redirects]]
  from = "http://osteopatia-paduszynski.pl/*"
  to = "https://osteopatia-paduszynski.pl/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.osteopatia-paduszynski.pl/*"
  to = "https://osteopatia-paduszynski.pl/:splat"
  status = 301
  force = true

# SPA fallback removed - not needed for static Astro site
# This was causing all pages to redirect to index.html

[context.production.environment]
  NODE_ENV = "production"

# Basic security headers - simplified for Netlify compatibility
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"

# Cache static assets
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"