[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Minimal SSL headers for Edge compatibility only
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000"