[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Podstawowe nagłówki bezpieczeństwa
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Specific headers for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    
# Specific headers for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Service Worker headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/javascript"

# Podstawowe przekierowania HTTP -> HTTPS (bez force)
[[redirects]]
  from = "http://osteopatia-paduszynski.pl/*"
  to = "https://osteopatia-paduszynski.pl/:splat"
  status = 301

[[redirects]]
  from = "http://www.osteopatia-paduszynski.pl/*"
  to = "https://osteopatia-paduszynski.pl/:splat"
  status = 301

[[redirects]]
  from = "https://www.osteopatia-paduszynski.pl/*"
  to = "https://osteopatia-paduszynski.pl/:splat"
  status = 301