[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Force HTTPS redirect
[[redirects]]
  from = "http://osteopatia-paduszynski.pl/*"
  to = "https://osteopatia-paduszynski.pl/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.osteopatia-paduszynski.pl/*"
  to = "https://osteopatia-paduszynski.pl/:splat"
  status = 301
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

# Security and Cache headers for HTML with SSL mobile fix
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    # Mobile-friendly cache without must-revalidate to avoid SSL protocol errors
    Cache-Control = "public, max-age=300"
    # Mobile-friendly HSTS without preload to avoid SSL protocol errors
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    # Gentler CSP for mobile compatibility
    Content-Security-Policy = "upgrade-insecure-requests; block-all-mixed-content"
    # Additional headers for mobile SSL compatibility
    Vary = "Accept-Encoding"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"